id: PD22E43A4
initial_creation_type: input
source_metadata:
  title: Jamgön Kongtrul Lodrö Thaye Series
  language: en
  description: Works by or about the great nineteenth century master Jamgön Kongtrul
    Lodrö Thaye ('jam mgon kong sprul blo gros mtha' yas, 1813–1899), one of the pioneers
    of the Rimé movement
  volume:
    35ec98f9a0ba4cfd91ed71ed534398fe:
      title: Advice to Lhawang Tashi
      parent: Advice
    dc951721b240455a8e6de76ce4312235:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    d3e6942c2b214f66b5218155d57ec850:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    aec34a5591794ded91ddc05b9a3564ac:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    997bf8a9e05343cdaecad49dc7b2a1e9:
      title: Prayer for Peace and Stability in Tibet
      parent: Aspiration Prayers
    aafd0ffc2c6c4786a01a0df157ffad5b:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Aspiration Prayers
    f09ad93ec3234f9896ad3ee7dbe02936:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    e60b48f98e2e49ebbe68be7f01559f2b:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    c1375950a82b4c109c1d4e389af6d01a:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    b5f1d023b1144473bc90322b42adafc8:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Calling the Guru From Afar
    8cc800c656e840faae0aa492a52ca36f:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Commentaries
    6ab4a6a4dbc249dc8c53a907139d942f:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Empowerment Rites
    7c2e22b672f54afa890f0185403957b8:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Fire Offering
    1cecfae253214b25b22363293c54f64e:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Guru Rinpoche Prayers
    9dd2172d7e8d41249fcd41de52541d4c:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    f4d06155796c4957b10eeea218f93bd1:
      title: A Short Supplication to Tārā
      parent: Prayers
    5ab1760ee6504937bf292bcbb974db46:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    fabe254b4ffc4defa4f3a0ca3dbe2132:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    c7c9189438444e6bad1f1285faad1ba3:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    2e779b909f5f4957bbaf4ecd5e933271:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Prayers
    74482fe9b72d4e3f8850bd35e2d74174:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    23f37064c40840eaab52b83d338c7090:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Saving Lives
    d8863c3e32224bd580f4cdab3d79db8c:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Swift Rebirth Prayers
    1b84dcc11f614a50bcc6fc1df45a6064:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Tsok
    73a0659334494401a9ec8df8cdd2646b:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T23:32:21.216146'
last_modified_at: '2022-02-28T23:32:21.216152'
